import React from 'react';
import { Models as ModelsApp } from "mrmkmcib-app";
import { Models } from "mrmkmcib-crm";
import { Enums } from '../Enums';
import * as ModelsNoteList from "../models/ModelsNoteList";
import Error from "../models/Error";
declare const ViewNoteList: React.StatelessComponent<IProps>;
export interface IProps {
    testID: string;
    performEdit: ModelsNoteList.PERFORM_EDIT;
    performCancel: ModelsNoteList.PERFORM_CANCEL;
    performSave: ModelsNoteList.PERFORM_SAVE;
    returnToPreviousNavigationArea: ModelsNoteList.RETURN_TO_PREVIOUS_NAVIGATION_AREA;
    navigateToNoteScreen: ModelsNoteList.NAVIGATE_TO_NOTE_SCREEN;
    navigateToNoteCreateScreen: ModelsNoteList.NAVIGATE_TO_NOTE_CREATE_SCREEN;
    isEditorMode: boolean;
    noteListSaveInProgress: boolean;
    noteListSaveError: Error | null;
    performSaveNote: ModelsNoteList.PERFORM_SAVE_NOTE;
    performEditNote: ModelsNoteList.PERFORM_EDIT_NOTE;
    performNoteAdd: ModelsNoteList.PERFORM_NOTE_ADD;
    performNoteDelete: ModelsNoteList.PERFORM_NOTE_DELETE;
    navigateToNoteTypePickerScreen: ModelsNoteList.NAVIGATE_TO_NOTE_TYPE_PICKER_SCREEN;
    navigateToCurrentNoteTypePickerScreen: ModelsNoteList.NAVIGATE_TO_CURRENT_NOTE_TYPE_PICKER_SCREEN;
    navigateToViewNotes: ModelsNoteList.NAVIGATE_TO_VIEW_NOTE;
    navigateBack: ModelsNoteList.NAVIGATE_BACK;
    navigateBackNote: ModelsNoteList.NAVIGATE_BACK_NOTE;
    performNoteUpdate: ModelsNoteList.PERFORM_NOTE_UPDATE;
    performNoteTextUpdate: ModelsNoteList.PERFORM_NOTE_TEXT_UPDATE;
    performNoteTypeUpdate: ModelsNoteList.PERFORM_NOTE_TYPE_UPDATE;
    performContainerReset: ModelsNoteList.PERFORM_CONTAINER_RESET;
    performCloseNoteDeletePanel: ModelsNoteList.PERFORM_CLOSE_NOTE_DELETE_PANEL;
    performOpenNoteDeletePanel: ModelsNoteList.PERFORM_OPEN_NOTE_DELETE_PANEL;
    currentAgent: Models.Agent;
    currentCustomerManaged: Models.CustomerManaged;
    inputNoteList: Models.NoteList;
    currentNoteIndex: number | null;
    currentNote: Models.Note;
    classifierDictionary: ModelsApp.ClassifierDictionary;
    isExpandedMode: boolean;
    noteListDeletePanel: Models.Note[];
    noteListContextMode: Enums.NoteListContextMode;
    isVisibleNoteListErrorModalWindow: boolean;
    performChangeVisibleNoteListErrorModal: ModelsNoteList.PERFORM_CHANGE_VISIBLE_NOTE_LIST_ERROR_MODAL;
}
export default ViewNoteList;
