import React from 'react';
import { Models } from "mrmkmcib-crm";
import * as ModelsGszActivityExclude from "../models/ModelsGszActivityExclude";
import Error from "../models/Error";
import { Models as ModelsApp } from 'mrmkmcib-app';
export interface IProps {
    searchInProgress: boolean;
    navigateToCustomerPickerScreen: ModelsGszActivityExclude.NAVIGATE_TO_CUSTOMER_PICKER_SCREEN;
    performInputSearchManagedOnly: ModelsGszActivityExclude.PERFORM_INPUT_SEARCH_MANAGED_ONLY;
    performInputSearch: ModelsGszActivityExclude.PERFORM_INPUT_SEARCH;
    performSearchReset: ModelsGszActivityExclude.PERFORM_SEARCH_RESET;
    performSearch: ModelsGszActivityExclude.PERFORM_SEARCH;
    performInputCustomer: ModelsGszActivityExclude.PERFORM_INPUT_CUSTOMER;
    performInputComment: ModelsGszActivityExclude.PERFORM_INPUT_COMMENT;
    performCancel: ModelsGszActivityExclude.PERFORM_CANCEL;
    performSave: ModelsGszActivityExclude.PERFORM_SAVE;
    callPostGszActivityExcludeCreate: ModelsGszActivityExclude.CALL_POST_GSZ_ACTIVITY_EXCLUDE_CREATE;
    navigateBack: ModelsGszActivityExclude.NAVIGATE_BACK;
    performContainerReset: ModelsGszActivityExclude.PERFORM_CONTAINER_RESET;
    inputSearch: string;
    customerSearchList: Models.CustomerList;
    inputSearchManagedOnly: boolean;
    inputCustomer: Models.Customer;
    inputComment: string;
    operationUuid: string;
    gszActivityExcludeValidationComment: string | null;
    gszActivityExcludeValidationCustomer: string | null;
    activitySave: boolean;
    currentUser: ModelsApp.Employee;
    activitySaveInProgress: boolean;
    activitySaveError: Error | null;
    activityExcludeCreate: boolean;
    activityExcludeCreateFetching: boolean;
    activityExcludeCreateError: Error | null;
    activityExcludeCreateCachedDate: Date | null;
    currentCustomerManaged: Models.CustomerManaged;
    currentGsz: Models.Gsz;
    navigateToMemberListScreen: ModelsGszActivityExclude.NAVIGATE_TO_MEMBER_LIST_SCREEN;
    performCancelSearchCustomer: ModelsGszActivityExclude.NAVIGATE_TO_MEMBER_LIST_SCREEN;
    memberList: Models.MemberList;
    testID: string;
    isVisibleModalActivityError: boolean;
    performChangeVisibleErrorModal: ModelsGszActivityExclude.PERFORM_CHAGNE_VISIBLE_ERROR_MODAL;
    searchError: Error | null;
}
declare const ViewGszActivityExclude: React.StatelessComponent<IProps>;
export default ViewGszActivityExclude;
