import React from 'react';
import * as ModelsDealStages from "../models/ModelsDealStages";
import { Models as ModelsApp } from 'mrmkmcib-app';
import { Models } from 'mrmkmcib-crm';
import Error from '../models/Error';
export interface IPropsStageDetails {
    stage: Models.DealStage;
}
export declare const StageDetails: React.StatelessComponent<IPropsStageDetails>;
declare const ViewDealStages: React.StatelessComponent<IProps>;
export interface IProps {
    testID: string;
    currentDeal: Models.Deal;
    isAccessibleStages: boolean;
    stageList: Array<Models.DealStage>;
    selectedStage: Models.DealStage;
    activePosition: number;
    crmStages: Models.CrmStagesList;
    progress: number;
    system: string | null;
    isInputDealDateEnable: boolean;
    isRejection: boolean;
    inputRejection: ModelsApp.Classifier;
    saveDealAdditionalFieldsInProgress: boolean;
    saveDealAdditionalFieldsError: Error | null;
    saveDealStageInProgress: boolean;
    saveDealStageError: Error | null;
    isReadOnlyStages: boolean;
    receivingInputParametersInProgress: boolean;
    receivingInputParametersError: Error | null;
    inputDealDate: Date | null;
    currentStageStatus: ModelsDealStages.ICurrentStageStatus;
    currentStageTab: number;
    isErrorEnable: boolean;
    isSaveStageEnable: boolean;
    classifierDictionary: ModelsApp.ClassifierDictionary;
    accessibleStageList: ModelsApp.ClassifierList;
    dealPossibleStageList: Models.DealPossibleStageList;
    dealHistoryStageList: Models.DealHistoryStageList;
    dealStageTracking: Models.DealStageTracking;
    inputStage: ModelsApp.Classifier;
    inputEquivalentSumString: string | null;
    inputCurrency: ModelsApp.Classifier | null;
    errorMessage: string;
    isSetMainClientManager: boolean;
    isSetMainCreditOfficer: boolean;
    isSetMemberMonitoring: boolean;
    isSetPlannedFinishDate: boolean;
    isSetCloseReason: boolean;
    isSetCurrency: boolean;
    isSetClientStageChanges: boolean;
    isSaveAdditionalFieldsEnable: boolean;
    isButtonPopoverOpenedMainClientManager: boolean;
    isButtonPopoverOpenedMainCreditOfficer: boolean;
    isButtonPopoverOpenedMemberMonitoring: boolean;
    isDealStagesSavePopoverOpened: boolean;
    inputMainClientManager: ModelsApp.Employee | null;
    inputMainCreditOfficer: ModelsApp.Employee | null;
    inputMemberMonitoring: ModelsApp.Employee | null;
    inputComment: string;
    isStageListEnable: boolean;
    performInputComment: ModelsDealStages.PERFORM_INPUT_STRING;
    performSelectRejection: ModelsDealStages.PERFORM_SELECT_REJECTION;
    performInputDealDate: ModelsDealStages.PERFORM_INPUT_DEAL_DATE;
    performInputEquivalentSumString: ModelsDealStages.PERFORM_INPUT_EQUIVALENT_SUM_STRING;
    performReceivingInputParameters: ModelsDealStages.PERFORM_RECEIVING_INPUT_PARAMETERS;
    navigateToStageDetails: ModelsDealStages.NAVIGATE_TO_STAGE_DETAILS;
    navigateToStageEditor: ModelsDealStages.NAVIGATE_TO_STAGE_EDITOR;
    performSaveDealAdditionalFields: ModelsDealStages.PERFORM_SAVE_DEAL_ADDITIONAL_FIELDS;
    performSaveDealStage: ModelsDealStages.PERFORM_SAVE_DEAL_STAGE;
    navigateToCurrencyPickerScreen: ModelsDealStages.NAVIGATE_TO_CURRENCY_PICKER_SCREEN;
    navigateBack: ModelsDealStages.NAVIGATE_BACK;
    navigateBackWithResetData: ModelsDealStages.NAVIGATE_BACK_WITH_RESET_DATA;
    navigateToAdditionalFields: ModelsDealStages.NAVIGATE_TO_ADDITIONAL_FIELDS;
    navigateToPreviousForm: ModelsDealStages.NAVIGATE_TO_PREVIOUS_FORM;
    performChangeStageTab: ModelsDealStages.PERFORM_CHANGE_STAGE_TAB;
    performPopoverClientRoadMapHelpShow: ModelsDealStages.NO_PARAMS_VOID;
    performPopoverClientRoadMapHelpHide: ModelsDealStages.NO_PARAMS_VOID;
    isVisiblePopoverClientRoadMapHelp: boolean;
    performClientRoadMapActivate: ModelsDealStages.NO_PARAMS_VOID;
    performClientRoadMapNext: ModelsDealStages.NO_PARAMS_VOID;
    showButtonPopoverMainClientManager: ModelsDealStages.SHOW_BUTTON_POPOVER_MAIN_CLIENT_MANAGER;
    showButtonPopoverMainCreditOfficer: ModelsDealStages.SHOW_BUTTON_POPOVER_MAIN_CREDIT_OFFICER;
    showButtonPopoverMemberMonitoring: ModelsDealStages.SHOW_BUTTON_POPOVER_MEMBER_MONITORING;
    showDealStagesSavePopover: ModelsDealStages.SHOW_DEAL_STAGES_SAVE_POPOVER;
    performPopoverClientRoadMapShow: ModelsDealStages.NO_PARAMS_VOID;
    performPopoverClientRoadMapHide: ModelsDealStages.NO_PARAMS_VOID;
    performSaveStage: ModelsDealStages.PERFORM_SAVE_STAGE;
    performInputEmployeeSourceMainClientManager: ModelsDealStages.PERFORM_INPUT_EMPLOYEE_SOURCE_MAIN_CLIENT_MANAGER;
    performInputEmployeeSourceMainCreditOfficer: ModelsDealStages.PERFORM_INPUT_EMPLOYEE_SOURCE_MAIN_CREDIT_OFFICER;
    performInputEmployeeSourceMemberMonitoring: ModelsDealStages.PERFORM_INPUT_EMPLOYEE_SOURCE_MEMBER_MONITORING;
    onSaveDealStageButtonTap: ModelsDealStages.ON_SAVE_DEAL_STAGE_BUTTON_TAP;
    isVisiblePopoverClientRoadMap: boolean;
}
export default ViewDealStages;
