import * as ModelState from "../models/Models";
import { Models as ModelsApp } from "mrmkmcib-app";
import { Models } from "mrmkmcib-crm";
import { Enums } from '../Enums';
export declare const performInputCurrency: (value: ModelsApp.Classifier) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performChangeDisplayRefreshBarProductList: (value: boolean) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performInputEncumbrance: (value: Models.ProductEncumbrance) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performModalProductShow: () => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performModalProductHide: () => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const navigateToProduct: () => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const navigateProductListBack: () => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const navigateToProductListScreen: (productType: Enums.ProductType) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const navigateToProductForecastEventInfoScreen: (event: Models.ForecastEvent) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const navigateToProductForecastDealInfoScreen: (deal: Models.ForecastDeal) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const navigateProductForecastDealInfoScreenBack: () => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performProductListModalAlertShow: () => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performProductListModalAlertHide: () => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const filterProductList: (isActiveProductList: boolean) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const filterCreditProductList: (productList: Models.CreditProductList) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const filterBankGuaranteeProductList: (productList: Models.CreditProductList) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const filterCashManagementProductList: (productList: Models.SettlementAgreementProductList) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const filterPaymentAccountProductList: (productList: Models.SettlementAgreementProductList) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const filterCustomsPaymentProductList: (productList: Models.SettlementAgreementProductList) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const filterPackageProductList: (productList: Models.SettlementAgreementProductList) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const filterTariffPlanProductList: (productList: Models.SettlementAgreementProductList) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const filterDepositProductList: (productList: Models.DepositProductList) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const filterContractSdoProductList: (productList: Models.DepositProductList) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const filterContractNsoProductList: (productList: Models.DepositProductList) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const filterCorporateCardProductList: (productList: Models.CorporateCardProductList) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const filterEncashmentProductList: (productList: Models.EncashmentContractProductList) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const filterSelfEncashmentProductList: (productList: Models.EncashmentContractProductList) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const filterCurrencyControlProductList: (productList: Models.LegalInfoProductList) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const filterAcquiringProductList: (productList: Models.AcquiringProductList) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const filterDboProductList: (productList: Models.DboProductList) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const filterContractConstructorProductList: (productList: Models.UdboProductList) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const filterSalaryProductList: (productList: Models.SalaryProductList) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performContainerReset: () => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performSetForecastDealsToCreditProducts: () => (dispatch: Function, getState: () => ModelState.IRootState) => void;
