import * as ModelState from "../models/Models";
import { Models } from "mrmkmcib-crm";
import { Enums } from '../Enums';
export declare const performHideProduct: () => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performCreditProductShow: (value: Models.CreditProduct) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performCurrentCreditProductRefresh: () => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performBankGuaranteeProductShow: (value: Models.CreditProduct) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performCashManagementProductShow: (value: Models.SettlementAgreementProduct) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performPaymentAccountProductShow: (value: Models.SettlementAgreementProduct) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performCustomsPaymentProductShow: (value: Models.SettlementAgreementProduct) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performPackageProductShow: (value: Models.SettlementAgreementProduct) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performTariffPlanProductShow: (value: Models.SettlementAgreementProduct) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performDepositProductShow: (value: Models.DepositProduct) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performContractSdoProductShow: (value: Models.DepositProduct) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performContractNsoProductShow: (value: Models.DepositProduct) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performCorporateCardProductShow: (value: Models.CorporateCardProduct) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performEncashmentProductShow: (value: Models.EncashmentContractProduct) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performSelfEncashmentProductShow: (value: Models.EncashmentContractProduct) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performCurrencyControlProductShow: (value: Models.LegalInfoProduct) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performAcquiringProductShow: (value: Models.AcquiringProduct) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performDboProductShow: (value: Models.DboProduct) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performContractConstructorProductShow: (value: Models.UdboProduct) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performSalaryProductShow: (value: Models.SalaryProduct) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const inputProductStatus: (value: Enums.ProductStatus) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const inputCurrency: (value: Enums.Currency) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performContainerReset: () => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const navigateToProductFromPush: () => (dispatch: Function, getState: () => ModelState.IRootState) => void;
