import React from 'react';
import { Models } from "mrmkmcib-crm";
import { Enums } from '../../Enums';
import * as ModelsAppCRM from "../../models/ModelsAppCRM";
import * as ModelsCustomer from "../../models/ModelsCustomer";
import * as ModelsCustomerEditor from "../../models/ModelsCustomerEditor";
import * as ModelsProductList from "../../models/ModelsProductList";
import * as ModelsAgentList from "../../models/ModelsAgentList";
import Error from "../../models/Error";
export interface IProps {
    navigateToCustomerActivityIncludeScreen: ModelsCustomer.NAVIGATE_TO_CUSTOMER_ACTIVITY_INCLUDE_SCREEN;
    navigateToCustomerActivityExcludeScreen: ModelsCustomer.NAVIGATE_TO_CUSTOMER_ACTIVITY_EXCLUDE_SCREEN;
    closeCustomerActivityPanel: ModelsCustomer.CLOSE_CUSTOMER_ACTIVITY_PANEL;
    customerManaged: Models.CustomerManaged;
    isDashboardExpandedMode: boolean;
    navigateToOwnerAgentScreen: ModelsCustomer.NAVIGATE_TO_OWNER_AGENT_SCREEN;
    currentPopoverLimitItem: Enums.OldLimitItem;
    navigateToPopoverLimitItemScreen: ModelsCustomer.NAVIGATE_TO_POPOVER_LIMIT_ITEM_SCREEN;
    navigatePopoverLimitBack: ModelsCustomer.NAVIGATE_POPOVER_LIMIT_BACK;
    isVisibleModalCustomerEditor: boolean;
    performCustomerEditorShow: ModelsCustomerEditor.PERFORM_CUSTOMER_EDITOR_SHOW;
    isVisiblePopoverLimit: boolean;
    performLimitShow: ModelsCustomer.PERFORM_LIMIT_SHOW;
    performPopoverLimitHide: ModelsCustomer.PERFORM_POPOVER_LIMIT_HIDE;
    performChangeTab: ModelsCustomer.PERFORM_CHANGE_TAB;
    performPopoverHolderShow: ModelsCustomer.PERFORM_POPOVER_HOLDER_SHOW;
    performPopoverHolderHide: ModelsCustomer.PERFORM_POPOVER_HOLDER_HIDE;
    performPopoverCuratorShow: ModelsCustomer.PERFORM_POPOVER_CURATOR_SHOW;
    performPopoverCuratorHide: ModelsCustomer.PERFORM_POPOVER_CURATOR_HIDE;
    performPopoverOccasionListShow: ModelsCustomer.PERFORM_POPOVER_OCCASION_LIST_SHOW;
    performPopoverOccasionListHide: ModelsCustomer.PERFORM_POPOVER_OCCASION_LIST_HIDE;
    performPopoverNoteListShow: ModelsCustomer.PERFORM_POPOVER_NOTE_LIST_SHOW;
    performPopoverNoteListHide: ModelsCustomer.PERFORM_POPOVER_NOTE_LIST_HIDE;
    performPopoverProblemListShow: ModelsCustomer.PERFORM_POPOVER_PROBLEM_LIST_SHOW;
    performPopoverProblemListHide: ModelsCustomer.PERFORM_POPOVER_PROBLEM_LIST_HIDE;
    performPopoverOwnerShow: ModelsCustomer.PERFORM_POPOVER_OWNER_SHOW;
    performPopoverOwnerHide: ModelsCustomer.PERFORM_POPOVER_OWNER_HIDE;
    performNavigateToOwnerScreen: ModelsCustomer.PERFORM_NAVIGATE_TO_OWNER_SCREEN;
    navigateToCustomerScreen: ModelsCustomer.NAVIGATE_TO_CUSTOMER_SCREEN;
    callGetLimitNew: ModelsCustomer.CALL_GET_LIMIT_NEW;
    callGetLimitOld: ModelsCustomer.CALL_GET_LIMIT_OLD;
    performProductTypeListRefresh: ModelsCustomer.PERFORM_PRODUCT_TYPE_LIST_REFRESH;
    performCallGetForceRequestProductList: ModelsCustomer.PERFORM_CALL_GET_REQUEST_PRODUCT_LIST;
    performCallGetCachedRequestProductList: ModelsCustomer.PERFORM_CALL_GET_REQUEST_PRODUCT_LIST;
    performCallGetUncachedRequestProductList: ModelsCustomer.PERFORM_CALL_GET_REQUEST_PRODUCT_LIST;
    performCustomerOpen: ModelsAppCRM.PERFORM_CUSTOMER_OPEN;
    performGszOpen: ModelsAppCRM.PERFORM_GSZ_OPEN;
    navigateBack: ModelsAppCRM.NAVIGATE_BACK;
    currentCustomerId: string;
    currentCustomer: Models.Customer;
    currentCustomerManaged: Models.CustomerManaged;
    isVisiblePopoverHolder: boolean;
    isVisiblePopoverCurator: boolean;
    isVisiblePopoverOccasionList: boolean;
    isVisiblePopoverNoteList: boolean;
    isVisiblePopoverProblemList: boolean;
    isVisiblePopoverOwner: boolean;
    isVisibleModalActivityEditor: boolean;
    isVisibleModalPlanner: boolean;
    isVisibleModalEmailSend: boolean;
    isVisibleModalAssociateSearch: boolean;
    inputSearchAffiliateList: string;
    isSearchModeAffiliateList: boolean;
    affiliateSearchList: Models.CustomerList;
    performInputSearchAffiliateList: ModelsCustomer.PERFORM_INPUT_SEARCH_AFFILIATE_LIST;
    performAffiliateListSearch: ModelsCustomer.PERFORM_AFFILIATE_LIST_SEARCH;
    performSearchAffiliateListEnable: ModelsCustomer.PERFORM_SEARCH_AFFILIATE_LIST_ENABLE;
    performSearchAffiliateListDisable: ModelsCustomer.PERFORM_SEARCH_AFFILIATE_LIST_DISABLE;
    currentTab: Enums.CustomerManagedTab;
    customerFetching: boolean;
    customerError: Error | null;
    limitOld: Models.LimitOld;
    limitOldFetching: boolean;
    limitOldError: Error | null;
    limitOldCachedDate: Date | null;
    limit: Models.Limit;
    limitFetching: boolean;
    limitError: Error | null;
    limitCachedDate: Date | null;
    productListAgreementStatus: Enums.ProductListAgreementStatus;
    creditActiveProductList: Models.CreditProductList;
    creditActiveProductListFetching: boolean;
    creditActiveProductListUpdating: boolean;
    creditActiveProductListError: Error | null;
    creditActiveProductListCachedDate: Date | null;
    creditCloseProductList: Models.CreditProductList;
    creditCloseProductListFetching: boolean;
    creditCloseProductListError: Error | null;
    creditCloseProductListCachedDate: Date | null;
    depositActiveProductList: Models.DepositProductList;
    depositActiveProductListFetching: boolean;
    depositActiveProductListUpdating: boolean;
    depositActiveProductListError: Error | null;
    depositActiveProductListCachedDate: Date | null;
    depositCloseProductList: Models.DepositProductList;
    depositCloseProductListFetching: boolean;
    depositCloseProductListError: Error | null;
    depositCloseProductListCachedDate: Date | null;
    settlementAgreementActiveProductList: Models.SettlementAgreementProductList;
    settlementAgreementActiveProductListFetching: boolean;
    settlementAgreementActiveProductListUpdating: boolean;
    settlementAgreementActiveProductListError: Error | null;
    settlementAgreementActiveProductListCachedDate: Date | null;
    settlementAgreementCloseProductList: Models.SettlementAgreementProductList;
    settlementAgreementCloseProductListFetching: boolean;
    settlementAgreementCloseProductListUpdating: boolean;
    settlementAgreementCloseProductListError: Error | null;
    settlementAgreementCloseProductListCachedDate: Date | null;
    corporateCardActiveProductList: Models.CorporateCardProductList;
    corporateCardActiveProductListFetching: boolean;
    corporateCardActiveProductListUpdating: boolean;
    corporateCardActiveProductListError: Error | null;
    corporateCardActiveProductListCachedDate: Date | null;
    corporateCardCloseProductList: Models.CorporateCardProductList;
    corporateCardCloseProductListFetching: boolean;
    corporateCardCloseProductListUpdating: boolean;
    corporateCardCloseProductListError: Error | null;
    corporateCardCloseProductListCachedDate: Date | null;
    encashmentContractActiveProductList: Models.EncashmentContractProductList;
    encashmentContractActiveProductListFetching: boolean;
    encashmentContractActiveProductListUpdating: boolean;
    encashmentContractActiveProductListError: Error | null;
    encashmentContractActiveProductListCachedDate: Date | null;
    encashmentContractCloseProductList: Models.EncashmentContractProductList;
    encashmentContractCloseProductListFetching: boolean;
    encashmentContractCloseProductListUpdating: boolean;
    encashmentContractCloseProductListError: Error | null;
    encashmentContractCloseProductListCachedDate: Date | null;
    acquiringActiveProductList: Models.AcquiringProductList;
    acquiringActiveProductListFetching: boolean;
    acquiringActiveProductListUpdating: boolean;
    acquiringActiveProductListError: Error | null;
    acquiringActiveProductListCachedDate: Date | null;
    acquiringCloseProductList: Models.AcquiringProductList;
    acquiringCloseProductListFetching: boolean;
    acquiringCloseProductListUpdating: boolean;
    acquiringCloseProductListError: Error | null;
    acquiringCloseProductListCachedDate: Date | null;
    dboActiveProductList: Models.DboProductList;
    dboActiveProductListFetching: boolean;
    dboActiveProductListUpdating: boolean;
    dboActiveProductListError: Error | null;
    dboActiveProductListCachedDate: Date | null;
    dboCloseProductList: Models.DboProductList;
    dboCloseProductListFetching: boolean;
    dboCloseProductListUpdating: boolean;
    dboCloseProductListError: Error | null;
    dboCloseProductListCachedDate: Date | null;
    salaryActiveProductList: Models.SalaryProductList;
    salaryActiveProductListFetching: boolean;
    salaryActiveProductListUpdating: boolean;
    salaryActiveProductListError: Error | null;
    salaryActiveProductListCachedDate: Date | null;
    salaryCloseProductList: Models.SalaryProductList;
    salaryCloseProductListFetching: boolean;
    salaryCloseProductListUpdating: boolean;
    salaryCloseProductListError: Error | null;
    salaryCloseProductListCachedDate: Date | null;
    udboActiveProductList: Models.UdboProductList;
    udboActiveProductListFetching: boolean;
    udboActiveProductListUpdating: boolean;
    udboActiveProductListError: Error | null;
    udboActiveProductListCachedDate: Date | null;
    udboCloseProductList: Models.UdboProductList;
    udboCloseProductListFetching: boolean;
    udboCloseProductListUpdating: boolean;
    udboCloseProductListError: Error | null;
    udboCloseProductListCachedDate: Date | null;
    legalInfoProductList: Models.LegalInfoProductList;
    legalInfoProductListFetching: boolean;
    legalInfoProductListError: Error | null;
    legalInfoProductListCachedDate: Date | null;
    agentList: Models.AgentList;
    agentListFetching: boolean;
    agentListError: Error | null;
    currentOwner: Models.Owner;
    navigateToProductListScreen: ModelsProductList.NAVIGATE_TO_PRODUCT_LIST_SCREEN;
    navigateToAgentListScreen: ModelsCustomer.NAVIGATE_TO_AGENT_LIST_SCREEN;
    navigateToMemberListScreen: ModelsCustomer.NAVIGATE_TO_MEMBER_LIST_SCREEN;
    testID: string;
    callGetAgentList: ModelsAgentList.CALL_GET_AGENT_LIST;
}
declare const CustomerManagedTabOwnerList: React.StatelessComponent<IProps>;
export default CustomerManagedTabOwnerList;
