//
//  UFSIconType.h
//  UFSPlatform
//
//  Created by Daniel Kalintsev on 21.10.16.
//  Copyright © 2016 SberTech. All rights reserved.
//

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, UFSIconType) {
    UFSIconTypeMrmAdd,
    UFSIconTypeMrmArrowDown,
    UFSIconTypeMrmArrowUp,
    UFSIconTypeMrmBack,
    UFSIconTypeMrmBell,
    UFSIconTypeMrmBookmarkOff,
    UFSIconTypeMrmBookmarkOn,
    UFSIconTypeMrmBrick,
    UFSIconTypeMrmCalendar,
    UFSIconTypeMrmCamera,
    UFSIconTypeMrmChat,
    UFSIconTypeMrmCheckboxMinus,
    UFSIconTypeMrmCheckboxOff,
    UFSIconTypeMrmCheckboxOn,
    UFSIconTypeMrmClear,
    UFSIconTypeMrmClose,
    UFSIconTypeMrmComboChart,
    UFSIconTypeMrmCopy,
    UFSIconTypeMrmCrown,
    UFSIconTypeMrmDirectspeech,
    UFSIconTypeMrmDone,
    UFSIconTypeMrmDownload,
    UFSIconTypeMrmEdit,
    UFSIconTypeMrmFavorite,
    UFSIconTypeMrmFavorited,
    UFSIconTypeMrmFilter,
    UFSIconTypeMrmHamburger,
    UFSIconTypeMrmHint,
    UFSIconTypeMrmInfo,
    UFSIconTypeMrmKebab,
    UFSIconTypeMrmLink,
    UFSIconTypeMrmLock,
    UFSIconTypeMrmMail,
    UFSIconTypeMrmMan,
    UFSIconTypeMrmMap,
    UFSIconTypeMrmMeatball,
    UFSIconTypeMrmMinus,
    UFSIconTypeMrmPhone,
    UFSIconTypeMrmPin,
    UFSIconTypeMrmPlus,
    UFSIconTypeMrmPrint,
    UFSIconTypeMrmQRCode,
    UFSIconTypeMrmRadiobuttonOff,
    UFSIconTypeMrmRadiobuttonOn,
    UFSIconTypeMrmRefresh,
    UFSIconTypeMrmSearch,
    UFSIconTypeMrmShare,
    UFSIconTypeMrmTime,
    UFSIconTypeMrmTrash,
    UFSIconTypeMrmTrophy,
    UFSIconTypeSpecialCardAmex,
    UFSIconTypeSpecialCardGeneric,
    UFSIconTypeSpecialCardMaestro,
    UFSIconTypeSpecialCardMaster,
    UFSIconTypeSpecialCardMir,
    UFSIconTypeSpecialCardPro100,
    UFSIconTypeSpecialCardUek,
    UFSIconTypeSpecialCardVisa,
    UFSIconTypeSpecialDepositGeneric,
    UFSIconTypeSpecialDocsDoc,
    UFSIconTypeSpecialDocsGeneric,
    UFSIconTypeSpecialDocsImg,
    UFSIconTypeSpecialDocsPdf,
    UFSIconTypeSpecialDocsXls,
    UFSIconTypeSpecialStatusBell,
    UFSIconTypeSpecialStatusCall,
    UFSIconTypeSpecialStatusFlag,
    UFSIconTypeSpecialStatusMeet,
    UFSIconTypeSpecialStatusNew,
    UFSIconTypeSpecialStatusNewFlag,
    UFSIconTypeSpecialStatusPin
};
