import React from 'react';
import { Models as ModelsApp } from "mrmkmcib-app";
import { Models } from "mrmkmcib-crm";
import { Enums } from '../Enums';
import * as ModelsAppCRM from "../models/ModelsAppCRM";
import * as ModelsCustomer from "../models/ModelsCustomer";
import * as ModelsProductList from "../models/ModelsProductList";
import * as ModelsProduct from "../models/ModelsProduct";
import Error from "../models/Error";
export interface IProps {
    performInputCurrency: ModelsProductList.PERFORM_INPUT_CURRENCY;
    performInputEncumbrance: ModelsProductList.PERFORM_INPUT_ENCUMBRANCE;
    performModalProductHide: ModelsProductList.PERFORM_MODAL_PRODUCT_HIDE;
    navigateToProductListScreen: ModelsProductList.NAVIGATE_TO_PRODUCT_LIST_SCREEN;
    navigateToProductForecastDealInfoScreen: ModelsProductList.NAVIGATE_TO_PRODUCT_LIST_FORECAST_DEAL_INFO_SCREEN;
    navigateToProductForecastEventInfoScreen: ModelsProductList.NAVIGATE_TO_PRODUCT_LIST_FORECAST_PRODUCT_INFO_SCREEN;
    performContainerReset: ModelsProductList.PERFORM_CONTAINER_RESET;
    performChangeDisplayRefreshBarProductList: ModelsProductList.PERFORM_CHANGE_DISPLAY_REFRESH_BAR_PRODUCT_LIST;
    performCallGetForceRequestProductList: ModelsCustomer.PERFORM_CALL_GET_REQUEST_PRODUCT_LIST;
    performCallGetCachedRequestProductList: ModelsCustomer.PERFORM_CALL_GET_REQUEST_PRODUCT_LIST;
    performCallGetUncachedRequestProductList: ModelsCustomer.PERFORM_CALL_GET_REQUEST_PRODUCT_LIST;
    navigateBack: ModelsAppCRM.NAVIGATE_BACK;
    performAcquiringProductShow: ModelsProduct.PERFORM_ACQUIRING_PRODUCT_SHOW;
    performCreditProductShow: ModelsProduct.PERFORM_CREDIT_PRODUCT_SHOW;
    performBankGuaranteeProductShow: ModelsProduct.PERFORM_BANK_GUARANTEE_PRODUCT_SHOW;
    performCashManagementProductShow: ModelsProduct.PERFORM_CASH_MANAGEMENT_PRODUCT_SHOW;
    performPaymentAccountProductShow: ModelsProduct.PERFORM_PAYMENT_ACCOUNT_PRODUCT_SHOW;
    performCustomsPaymentProductShow: ModelsProduct.PERFORM_CUSTOMS_PAYMENT_PRODUCT_SHOW;
    performPackageProductShow: ModelsProduct.PERFORM_PACKAGE_PRODUCT_SHOW;
    performTariffPlanProductShow: ModelsProduct.PERFORM_TARIFF_PLAN_PRODUCT_SHOW;
    performDepositProductShow: ModelsProduct.PERFORM_DEPOSIT_PRODUCT_SHOW;
    performContractSdoProductShow: ModelsProduct.PERFORM_CONTRACT_SDO_PRODUCT_SHOW;
    performContractNsoProductShow: ModelsProduct.PERFORM_CONTRACT_NSO_PRODUCT_SHOW;
    performCorporateCardProductShow: ModelsProduct.PERFORM_CORPORATE_CARD_PRODUCT_SHOW;
    performEncashmentProductShow: ModelsProduct.PERFORM_ENCASHMENT_PRODUCT_SHOW;
    performSelfEncashmentProductShow: ModelsProduct.PERFORM_SELF_ENCASHMENT_PRODUCT_SHOW;
    performCurrencyControlProductShow: ModelsProduct.PERFORM_CURRENCY_CONTROL_PRODUCT_SHOW;
    performDboProductShow: ModelsProduct.PERFORM_DBO_PRODUCT_SHOW;
    performContractConstructorProductShow: ModelsProduct.PERFORM_CONTRACT_CONSTRUCTOR_PRODUCT_SHOW;
    performSalaryProductShow: ModelsProduct.PERFORM_SALARY_PRODUCT_SHOW;
    performProductListModalAlertShow: ModelsProductList.PERFORM_PRODUCT_LIST_MODAL_ALERT_SHOW;
    performProductListModalAlertHide: ModelsProductList.PERFORM_PRODUCT_LIST_MODAL_ALERT_HIDE;
    performCallEksRequestProductList: ModelsCustomer.PERFORM_CALL_EKS_REQUEST_PRODUCT_LIST;
    pollingError: Error | null;
    bhCachedDate: Date | null;
    currencyList: ModelsApp.ClassifierList;
    encumbranceList: Models.ProductEncumbranceList;
    inputCurrency: ModelsApp.Classifier;
    inputEncumbranceList: Models.ProductEncumbranceList;
    isVisibleModalProduct: boolean;
    currentProductListType: Enums.ProductType;
    currentCreditProductList: Models.CreditProductList;
    currentBankGuaranteeProductList: Models.CreditProductList;
    currentCashManagementProductList: Models.SettlementAgreementProductList;
    currentPaymentAccountProductList: Models.SettlementAgreementProductList;
    currentCustomsPaymentProductList: Models.SettlementAgreementProductList;
    currentPackageProductList: Models.SettlementAgreementProductList;
    currentTariffPlanProductList: Models.SettlementAgreementProductList;
    currentDepositProductList: Models.DepositProductList;
    currentContractSdoProductList: Models.DepositProductList;
    currentContractNsoProductList: Models.DepositProductList;
    currentCorporateCardProductList: Models.CorporateCardProductList;
    currentEncashmentProductList: Models.EncashmentContractProductList;
    currentSelfEncashmentProductList: Models.EncashmentContractProductList;
    currentCurrencyControlProductList: Models.LegalInfoProductList;
    currentAcquiringProductList: Models.AcquiringProductList;
    currentDboProductList: Models.DboProductList;
    currentContractConstructorProductList: Models.UdboProductList;
    currentSalaryProductList: Models.SalaryProductList;
    currentCustomerManaged: Models.CustomerManaged;
    creditActiveProductEksListFetching: boolean;
    creditCloseProductEksListFetching: boolean;
    settlementAgreementActiveProductEksListFetching: boolean;
    settlementAgreementCloseProductEksListFetching: boolean;
    depositActiveProductEksListFetching: boolean;
    depositCloseProductEksListFetching: boolean;
    corporateCardActiveProductEksListFetching: boolean;
    corporateCardCloseProductEksListFetching: boolean;
    encashmentContractActiveProductEksListFetching: boolean;
    encashmentContractCloseProductEksListFetching: boolean;
    acquiringActiveProductEksListFetching: boolean;
    acquiringCloseProductEksListFetching: boolean;
    dboActiveProductEksListFetching: boolean;
    dboCloseProductEksListFetching: boolean;
    udboActiveProductEksListFetching: boolean;
    udboCloseProductEksListFetching: boolean;
    salaryActiveProductEksListFetching: boolean;
    salaryCloseProductEksListFetching: boolean;
    legalInfoProductEksListFetching: boolean;
    creditActiveProductListFetching: boolean;
    creditCloseProductListFetching: boolean;
    creditActiveProductListError: Error | null;
    creditCloseProductListError: Error | null;
    depositActiveProductListFetching: boolean;
    depositCloseProductListFetching: boolean;
    depositActiveProductListError: Error | null;
    depositCloseProductListError: Error | null;
    settlementAgreementActiveProductListFetching: boolean;
    settlementAgreementActiveProductListError: Error | null;
    settlementAgreementCloseProductListFetching: boolean;
    settlementAgreementCloseProductListError: Error | null;
    encashmentContractActiveProductListFetching: boolean;
    encashmentContractCloseProductListFetching: boolean;
    encashmentContractActiveProductListError: Error | null;
    encashmentContractCloseProductListError: Error | null;
    corporateCardActiveProductListFetching: boolean;
    corporateCardCloseProductListFetching: boolean;
    corporateCardActiveProductListError: Error | null;
    corporateCardCloseProductListError: Error | null;
    acquiringActiveProductListFetching: boolean;
    acquiringCloseProductListFetching: boolean;
    acquiringActiveProductListError: Error | null;
    acquiringCloseProductListError: Error | null;
    dboActiveProductListFetching: boolean;
    dboCloseProductListFetching: boolean;
    dboActiveProductListError: Error | null;
    dboCloseProductListError: Error | null;
    salaryActiveProductListFetching: boolean;
    salaryCloseProductListFetching: boolean;
    salaryActiveProductListError: Error | null;
    salaryCloseProductListError: Error | null;
    udboActiveProductListFetching: boolean;
    udboCloseProductListFetching: boolean;
    udboActiveProductListError: Error | null;
    udboCloseProductListError: Error | null;
    legalInfoProductListFetching: boolean;
    legalInfoProductListError: Error | null;
    productListAgreementStatus: Enums.ProductListAgreementStatus;
    testID: string;
    isVisibleRefreshBar: boolean;
    isVisibleProductListModalAlert: boolean;
    currentDeal: Models.ForecastDeal;
    currentEvent: Models.ForecastEvent;
}
declare const ViewProductList: React.StatelessComponent<IProps>;
export default ViewProductList;
