import React from 'react';
import { Models as ModelsCrm, Models } from 'mrmkmcib-crm';
import { Models as ModelsApp } from 'mrmkmcib-app';
import { Enums } from '../Enums';
import * as ModelsAppCRM from '../models/ModelsAppCRM';
import * as ModelsDealEditor from '../models/ModelsDealEditor';
import * as ModelsDealList from '../models/ModelsDealList';
import Error from '../models/Error';
export declare const isCredit: (item: ModelsCrm.Deal) => boolean;
export interface IProps {
    performChangeTab: ModelsDealList.PERFORM_CHANGE_TAB;
    infoMessage: string | null;
    isCreateDealEnable: boolean;
    isButtonCreateVisible: boolean;
    isEditDealEnable: boolean;
    performDealListRefresh: ModelsDealList.PERFORM_DEAL_LIST_REFRESH;
    performDealListFlush: ModelsDealList.PERFORM_DEAL_LIST_REFRESH;
    performDealCreate: ModelsDealList.PERFORM_DEAL_CREATE;
    performContainerReset: ModelsDealList.PERFORM_CONTAINER_RESET;
    navigateToDealEditor: ModelsDealEditor.NAVIGATE_TO_DEAL_EDITOR;
    performDealOpen: ModelsAppCRM.PERFORM_DEAL_OPEN;
    navigateBack: ModelsAppCRM.NAVIGATE_BACK;
    currentTab: Enums.DealListTab;
    currentUser: ModelsApp.Employee;
    performPopoverFilterShow: ModelsDealList.PERFORM_POPOVER_FILTER_SHOW;
    performPopoverFilterHide: ModelsDealList.PERFORM_POPOVER_FILTER_HIDE;
    performFilterApply: ModelsDealList.PERFORM_FILTER_APPLY;
    performFilterReset: ModelsDealList.PERFORM_FILTER_RESET;
    performInputFilterValue: ModelsDealList.PERFORM_INPUT_FILTER_VALUE;
    performFilterUnSelectProduct: ModelsDealList.PERFORM_CLASSIFIER_SELECTION;
    performFilterSelectProduct: ModelsDealList.PERFORM_CLASSIFIER_SELECTION;
    performFilterSelectStage: ModelsDealList.PERFORM_CLASSIFIER_SELECTION;
    performFilterSelectRole: ModelsDealList.PERFORM_CLASSIFIER_SELECTION;
    performFilterSelectCurrency: ModelsDealList.PERFORM_CLASSIFIER_SELECTION;
    performFilterSelectDateFrom: ModelsDealList.PERFORM_DATE_SELECTION;
    performFilterSelectDateTo: ModelsDealList.PERFORM_DATE_SELECTION;
    filterPopoverNavigateBack: ModelsDealList.NAVIGATE_POPOVER_BACK;
    filtersEditorOpened: Models.DealListFilter | null;
    filtersEditorClosed: Models.DealListFilter | null;
    filtersActiveOpened: Models.DealListFilter | null;
    filtersActiveClosed: Models.DealListFilter | null;
    filteredStagesList: ModelsApp.ClassifierList;
    filteredCurrencyList: ModelsApp.ClassifierList;
    filterPopoverNavigateToStage: ModelsDealList.NAVIGATE_IN_POPOVER;
    filterPopoverNavigateToRole: ModelsDealList.NAVIGATE_IN_POPOVER;
    filterPopoverNavigateToProduct: ModelsDealList.NAVIGATE_IN_POPOVER;
    filterPopoverNavigateToCurrency: ModelsDealList.NAVIGATE_IN_POPOVER;
    filterPopoverNavigateToDateFrom: ModelsDealList.NAVIGATE_IN_POPOVER;
    filterPopoverNavigateToDateTo: ModelsDealList.NAVIGATE_IN_POPOVER;
    dealListPageCachedDate: Date | null;
    classifierDictionary: ModelsApp.ClassifierDictionary;
    isVisiblePopoverFilter: boolean;
    dealOpenedList: Models.DealList;
    dealClosedList: Models.DealList;
    refresh: boolean;
    refreshInProgress: boolean;
    refreshError: Error | null;
    currentCustomerManaged: Models.CustomerManaged;
    testID: string;
    startAnimation: boolean;
    navigateToDealListSearchScreen: ModelsDealList.NAVIGATE_TO_DEAL_LIST_SEARCH_SCREEN;
}
declare const ViewDealList: React.StatelessComponent<IProps>;
export default ViewDealList;
