import { Models as ModelsApp } from "mrmkmcib-app";
import { Models as ModelsScheduler } from "mrmkmcib-scheduler";
import { Enums } from '../Enums';
import { Models } from "mrmkmcib-crm";
import * as ModelsMemberList from "../models/ModelsMemberList";
import Error from "../models/Error";
export interface IStateProps {
    currentActivity: ModelsScheduler.Activity;
    currentDeal: Models.Deal;
    currentCustomerManaged: Models.CustomerManaged;
    memberList: Models.MemberList;
    isEditorMode: boolean;
    isExpandedMode: boolean;
    isVisiblePopoverAdd: boolean;
    inputMemberSearch: string;
    inputMemberSearchSelected: ModelsApp.Employee;
    inputMemberRole: ModelsApp.Classifier;
    memberSearchList: Models.MemberList;
    memberSearchListFetching: boolean;
    memberSearchListError: Error | null;
    memberSearchListCachedDate: Date | null;
    currentGsz: Models.Gsz;
    currentMode: Enums.MemberListMode;
    classifierDictionary: ModelsApp.ClassifierDictionary;
    memberSearchListLocal: Models.MemberList;
    inputEmployeeSource: Enums.MemberListEmployeeSource;
    inputMemberSearchLocal: string;
    isSelectEmployeeLocalSearch: boolean;
    isSearchCompleted: boolean;
    isEditorEnabled: boolean;
    memberListSaveInProgress: boolean;
    memberListSaveError: Error | null;
    isEditingMemberList: boolean;
    customerForActivityError: Error | null;
    customerForActivityFetching: boolean;
    isDealCardOwner: boolean;
    isLocalSearch: boolean;
    isValidSearchString: boolean;
}
export interface IDispatchProps {
    performMemberListRefresh: ModelsMemberList.PERFORM_MEMBER_LIST_REFRESH;
    performEdit: ModelsMemberList.PERFORM_EDIT;
    performCancel: ModelsMemberList.PERFORM_CANCEL;
    performPopoverAddShow: ModelsMemberList.PERFORM_POPOVER_ADD_SHOW;
    performPopoverAddHide: ModelsMemberList.PERFORM_POPOVER_ADD_HIDE;
    navigateToMemberSearchScreen: ModelsMemberList.NAVIGATE_TO_MEMBER_SEARCH_SCREEN;
    performInputMemberSearch: ModelsMemberList.PERFORM_INPUT_MEMBER_SEARCH;
    callGetMemberSearchList: ModelsMemberList.CALL_GET_MEMBER_SEARCH_LIST;
    performMemberSearchListSelect: ModelsMemberList.PERFORM_MEMBER_SEARCH_LIST_SELECT;
    navigateToMemberRolePickerScreen: ModelsMemberList.NAVIGATE_TO_MEMBER_ROLE_PICKER_SCREEN;
    performMemberRoleSelect: ModelsMemberList.PERFORM_MEMBER_ROLE_SELECT;
    navigateToMemberListScreen: ModelsMemberList.NAVIGATE_TO_MEMBER_LIST_SCREEN;
    performSave: ModelsMemberList.PERFORM_SAVE;
    performMemberDelete: ModelsMemberList.PERFORM_MEMBER_DELETE;
    performMemberActionMenuSwitch: ModelsMemberList.PERFORM_MEMBER_ACTION_MENU_SWITCH;
    navigateBack: ModelsMemberList.NAVIGATE_BACK;
    performNavigateToMemberScreen: ModelsMemberList.PERFORM_NAVIGATE_TO_MEMBER_SCREEN;
    performContainerReset: ModelsMemberList.PERFORM_CONTAINER_RESET;
    navigateMemberListScreenBack: ModelsMemberList.NAVIGATE_MEMBER_LIST_SCREEN_BACK;
    swapContextMemberListToActivity: ModelsMemberList.SWAP_CONTEXT_MEMBER_LIST_TO_ACTIVITY;
    navigateSearchMemberListScreenBack: ModelsMemberList.NAVIGATE_SEARCH_MEMBER_LIST_SCREEN_BACK;
    navigateToMemberSearchLocalScreen: ModelsMemberList.NAVIGATE_TO_MEMBER_SEARCH_LOCAL_SCREEN;
    performInputMemberSearchLocal: ModelsMemberList.PERFORM_INPUT_MEMBER_SEARCH_LOCAL;
    performInputEmployeeSource: ModelsMemberList.PERFORM_INPUT_EMPLOYEE_SOURCE;
    performInputEmployeeSourceActivity: ModelsMemberList.PERFORM_INPUT_EMPLOYEE_SOURCE_ACTYVITY;
    navigateToSelectMemberIsGeneralScreen: ModelsMemberList.NAVIGATE_TO_SELECT_MEMBER_IS_GENERAL_SCREEN;
    performSelectGeneralMember: ModelsMemberList.PERFORM_GENERAL_MEMBER_SELECT;
    performResetAndReturn: ModelsMemberList.PERFORM_RESET_AND_RETURN;
    performCancelSaveMemberListError: ModelsMemberList.PERFORM_CANCEL_SAVE_MEMBER_LIST_ERROR;
    navigateBackFromMembersSearchPage: ModelsMemberList.NAVIGATE_BACK_FROM_MEMBERS_SEARCH_PAGE;
    performSearch: ModelsMemberList.PERFORM_SEARCH;
}
export declare type IMemberListProps = IStateProps & IDispatchProps & {
    testID: string;
};
declare const _default: any;
export default _default;
