import { Enums as EnumsAppAll } from "mrmkmcib-app";
import { Models as ModelsApp } from "mrmkmcib-app";
import { Enums } from '../Enums';
import { Models } from "mrmkmcib-crm";
import * as ModelsAppCRM from "../models/ModelsAppCRM";
import * as ModelsDealEditor from "../models/ModelsDealEditor";
import * as ModelsDeal from "../models/ModelsDeal";
import * as ModelsDealAttachments from '../models/ModelsDealAttachments';
import Error from "../models/Error";
export interface IStateProps {
    isDealExpandedMode: boolean;
    isEditDealEnable: boolean;
    currentDeal: Models.Deal;
    currentDealId: string;
    dealRoute: Array<Models.DealRoute>;
    currentMode: Enums.DealMode;
    isExtraInfoExpanded: boolean;
    agreementPopoverData: Models.DealAgreement | null;
    agreementPopoverTarget: string | null;
    expandedAgreementRowIndex: number;
    approvedStatuses: string;
    decisionPopoverData: Models.DealDecisionPopoverData | null;
    decisionPopoverTarget: string | null;
    isVisiblePopoverDecision: boolean;
    isVisibleModalPhaseSwitchQuestion: boolean;
    isVisibleModalDealCloseResult: boolean;
    currentDealPhase: ModelsApp.Classifier;
    inputDealCloseResult: ModelsApp.Classifier;
    refresh: boolean;
    refreshInProgress: boolean;
    navigationInProgress: boolean;
    refreshError: Error | null;
    currentDealFetching: boolean;
    currentDealError: Error | null;
    currentDealCachedDate: Date | null;
    classifierDictionary: ModelsApp.ClassifierDictionary;
    currentCustomerManaged: Models.CustomerManaged;
    currentUser: ModelsApp.Employee;
    agentList: Models.AgentList;
    agentListFetching: boolean;
    agentListError: Error | null;
    dealCrmStages: Models.CrmStagesList;
    dealCrmStagesFetching: boolean;
    dealCrmStagesError: Error | null;
    isReadOnlyStages: boolean;
    currentStageTab: number;
    selectedStage: Models.DealStage | null;
    isVisiblePopoverClientRoadMapHelp: boolean;
    isVisiblePopoverClientRoadMap: boolean;
    dealAgentListFetching: boolean;
    dealAgentListError: Error | null;
    dealAgentListCachedDate: Date | null;
    dealAgentList: Models.AgentList;
    navigationType: EnumsAppAll.NavigationType | null;
    dealAttachments: Models.IDealAttachmentList;
    dealAttachmentsError: Models.Error | null;
    dealAttachmentsFetching: boolean;
}
export interface IDispatchProps {
    navigateToEmployee: ModelsDeal.NAVIGATE_TO_EMPLOYEE;
    navigateToAgreementEmployee: ModelsDeal.NAVIGATE_TO_AGREEMENT_EMPLOYEE;
    navigateToDealScreen: ModelsDeal.NAVIGATE_TO_DEAL_SCREEN;
    navigateToParentDealScreen: ModelsDeal.NAVIGATE_TO_DEAL_PARENT_SCREEN;
    performRefresh: ModelsDeal.PERFORM_REFRESH;
    performRefreshForce: ModelsDeal.PERFORM_REFRESH;
    performRefreshAttachmentsList: ModelsDealAttachments.PERFORM_REFRESH_ATTACHMENTS_LIST;
    refresh_callGetDeal: ModelsDeal.REFRESH_CALL_GET_DEAL;
    navigateToProductScreen: ModelsDeal.NAVIGATE_TO_PRODUCT_SCREEN;
    navigateToAgreementScreen: ModelsDeal.NAVIGATE_TO_AGREEMENT_SCREEN;
    navigateToSolutionListScreen: ModelsDeal.NAVIGATE_TO_SOLUTION_LIST_SCREEN;
    navigateToMemberListScreen: ModelsDeal.NAVIGATE_TO_MEMBER_LIST_SCREEN;
    performExtraInfoToggle: ModelsDeal.PERFORM_EXTRA_INFO_TOGGLE;
    navigateToAgentListScreen: ModelsDeal.NAVIGATE_TO_AGENT_LIST_SCREEN;
    navigateToCommentListScreen: ModelsDeal.NAVIGATE_TO_COMMENT_LIST_SCREEN;
    navigateToPhaseScreen: ModelsDeal.NAVIGATE_TO_PHASE_SCREEN;
    navigateToNonLegalMembersScreen: ModelsDeal.NAVIGATE_TO_NON_LEGAL_MEMBERS_SCREEN;
    navigateToNonLegalMemberCard: ModelsDeal.NAVIGATE_TO_NON_LEGAL_MEMBER_CARD;
    performInputDealCloseResult: ModelsDeal.PERFORM_INPUT_DEAL_CLOSE_RESULT;
    performPhaseSwitch: ModelsDeal.PERFORM_PHASE_SWITCH;
    performPhaseSelect: ModelsDeal.PERFORM_PHASE_SELECT;
    performDealClose: ModelsDeal.PERFORM_DEAL_CLOSE;
    performModalPhaseSwitchQuestionHide: ModelsDeal.PERFORM_MODAL_PHASE_SWITCH_QUESTION_HIDE;
    performModalDealCloseResultHide: ModelsDeal.PERFORM_MODAL_DEAL_CLOSE_RESULT_HIDE;
    navigateDealBack: ModelsDeal.NAVIGATE_DEAL_BACK;
    performContainerReset: ModelsDeal.PERFORM_CONTAINER_RESET;
    performPopoverAgreementShow: ModelsDeal.PERFORM_POPOVER_AGREEMENT_SHOW;
    performPopoverAgreementHide: ModelsDeal.PERFORM_POPOVER_AGREEMENT_HIDE;
    performExpandAgreementRow: ModelsDeal.EXPAND_AGREEMENT_ROW;
    performPopoverDecisionShow: ModelsDeal.PERFORM_POPOVER_DECISION_SHOW;
    performPopoverDecisionHide: ModelsDeal.PERFORM_POPOVER_DECISION_HIDE;
    performCustomerOpen: ModelsAppCRM.PERFORM_CUSTOMER_OPEN;
    performChangeStageTab: ModelsAppCRM.PERFORM_CHANGE_STAGE_TAB;
    performPopoverClientRoadMapHelpShow: ModelsAppCRM.PERFORM_POPOVER_CLIENT_ROAD_MAP_HELP_SHOW;
    performPopoverClientRoadMapHelpHide: ModelsAppCRM.PERFORM_POPOVER_CLIENT_ROAD_MAP_HELP_HIDE;
    performClientRoadMapActivate: ModelsAppCRM.PERFORM_POPOVER_CLIENT_ROAD_MAP_ACTIVATE;
    performPopoverClientRoadMapShow: ModelsAppCRM.PERFORM_POPOVER_CLIENT_ROAD_MAP_SHOW;
    performPopoverClientRoadMapHide: ModelsAppCRM.PERFORM_POPOVER_CLIENT_ROAD_MAP_HIDE;
    navigateToStageDetails: ModelsAppCRM.NAVIGATE_TO_STAGE_DETAILS;
    performClientRoadMapNext: ModelsAppCRM.PERFORM_POPOVER_CLIENT_ROAD_MAP_ACTIVATE;
    navigateToDealEditor: ModelsDealEditor.NAVIGATE_TO_DEAL_EDITOR;
    navigateBack: ModelsAppCRM.NAVIGATE_BACK;
    navigateBackFromParent: ModelsDeal.NAVIGATE_BACK;
    navigateToDealAttachmentsScreen: ModelsDeal.NAVIGATE_BACK;
}
export declare type IDealProps = IStateProps & IDispatchProps & {
    testID: string;
};
declare const _default: any;
export default _default;
