import * as ModelState from '../models/Models';
import { Models } from 'mrmkmcib-crm';
export declare const performApplicationInit: () => (dispatch: Function) => void;
export declare const navigateBack: () => (dispatch: Function) => void;
export declare const downloadAttachment: (id: string) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performShowAuthWarning: (id: string) => (dispatch: Function) => void;
export declare const navigateToAuthWarningScreen: () => (dispatch: Function) => void;
export declare const navigateToAttachmentsFileViewerScreen: (fileId: string) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const navigateBackToAttachments: () => (dispatch: Function) => void;
export declare const performRefreshAttachmentsList: () => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performAttachmentReload: (id: string) => (dispatch: Function) => void;
export declare const performSearchModeEnable: () => (dispatch: Function) => void;
export declare const performSearchModeDisable: () => (dispatch: Function) => void;
export declare const callGetDealAttachments: () => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performInputDealAttachmentsSearch: (value: string) => (dispatch: Function) => void;
export declare const performDealAttachmentsSearch: () => (dispatch: Function) => void;
export declare const performPopoverDealAttachmentsShow: (dealCurrentAttachment: Models.DealAttachment) => (dispatch: Function) => void;
export declare const performPopoverDealAttachmentsHide: () => (dispatch: Function) => void;
export declare const performShowModalFileTypeError: (fileType: string) => (dispatch: Function) => void;
export declare const performHideModalFileTypeError: () => (dispatch: Function) => void;
export declare const performSetCurrentAttachment: (dealCurrentAttachment: Models.DealAttachment) => (dispatch: Function, getState: () => ModelState.IRootState) => void;
export declare const performResetCurrentAttachment: () => (dispatch: Function) => void;
export declare const performUnsupportedTypeBarHide: () => (dispatch: Function) => void;
